
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: select_cars_exculsively
    description: Select only Cars data from the data
    columns: 
      - name: time
        description: Time in seconds 
        tests: 
          - not_null 

      - name: traveled_d
        description: The distance traveled in meters
        tests:
          - not_null

      - name: avg_speed
        description: The average speed of vehicle in km/h
        tests:
          - not_null

      - name: lat
        description: Latitude of the vehicle
        tests:
          - not_null

      - name: lon
        description: Longitude of the vehicle
        tests:  
          - not_null

      - name: speed,
        description: Speed of the vehicle in km/h
        tests: 
          # - not_null

      - name: lon_acc
        description: Latitude acceleration of the vehicle in m/sec2
        tests: 
          - not_null

      - name: lat_acc
        description: Longitude acceleration of the vehicle in m/sec2
        tests: 
          - not_null

 
