 
postgres_new:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      pass: test1234
      port: 5432
      dbname: traffic
      schema: public
      threads: 10